source 'https://rubygems.org'
gem 'sinatra', '1.4.5'
gem 'haml', '3.1.8'
gem 'redis'
gem 'redis-pool'
gem 'redis-namespace'
gem 'nokogiri'
gem 'therubyracer'
gem 'coffee-filter'
gem 'algorithms'
gem 'redcarpet'
gem 'rack-session-redis', require: 'rack/session/redis'
group :development do
	gem 'shotgun'
end
